### PR TITLE
fix: do not log DEBUG lines by default

### LINKED ISSUE #164: Should log debug by default
After upgrading to release 0.2.0 I notice a lot of additional logging. Example:

```json
2023-02-01T12:51:26.039Z INFO Patching CIS status {"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "Job": {"name":"application-training-and-simulation-gui-app-659d9-a563c","namespace":"image-scanner-jobs"}, "namespace": "image-scanner-jobs", "name": "application-training-and-simulation-gui-app-659d9-a563c", "reconcileID": "fd07aaa4-4471-431f-a227-ed1054945ec6", "status": "Succeeded"}
```

I think this is debug logging that was added in https://github.com/statnett/image-scanner-operator/pull/139

### PR DESCRIPTION
**Pull request by padlar**
Signed-off-by: Sunil Shivanand <sunil.shivanand@statnett.no>

Fixes #164.

### CODE REVIEW

**Review by erikgb — CHANGES_REQUESTED** [review]
We would like to see these log messages when running the e2e-tests. Shouldn't we modify something in the e2e test config?

**Comment by erikgb** [comment]
@padlar Can you take another round on this one? I would like to include this in a new patch release.

**Comment by padlar** [comment]
Just verified that the `go test` dumps debug lines on error
```
/Users/padlar/sandbox/image-scanner-operator/internal/controller/stas/scan_job_controller_test.go:78

  Timeline >>
  2023-02-02T11:35:47+01:00	INFO	Reconciling	{"controller": "containerimagescan", "controllerGroup": "stas.statnett.no", "controllerKind": "ContainerImageScan", "ContainerImageScan": {"name":"application-example-app-a309a","namespace":"default"}, "namespace": "default", "name": "application-example-app-a309a", "reconcileID": "e71411bb-41f4-4c59-9605-732f047ff310"}
  2023-02-02T11:35:47+01:00	INFO	Reconciling	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "Job": {"name":"application-example-app-a309a-ab8ae","namespace":"image-scanner-jobs"}, "namespace": "image-scanner-jobs", "name": "application-example-app-a309a-ab8ae", "reconcileID": "0a69077b-e648-4807-97e3-c6fb140a8d85"}
  2023-02-02T11:35:47+01:00	DEBUG	Reconciling	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "Job": {"name":"application-example-app-a309a-ab8ae","namespace":"image-scanner-jobs"}, "namespace": "image-scanner-jobs", "name": "application-example-app-a309a-ab8ae", "reconcileID": "0a69077b-e648-4807-97e3-c6fb140a8d85", "status": {"succeeded":1}}
  2023-02-02T11:35:47+01:00	DEBUG	Patching CIS status	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "Job": {"name":"application-example-app-a309a-ab8ae","namespace":"image-scanner-jobs"}, "namespace": "image-scanner-jobs", "name": "application-example-app-a309a-ab8ae", "reconcileID": "0a69077b-e648-4807-97e3-c6fb140a8d85", "status": "Succeeded"}
  2023-02-02T11:35:50+01:00	DEBUG	Patched CIS status	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "Job": {"name":"application-example-app-a309a-ab8ae","namespace":"image-scanner-jobs"}, "namespace": "image-scanner-jobs", "name": "application-example-app-a309a-ab8ae", "reconcileID": "0a69077b-e648-4807-97e3-c6fb140a8d85", "reason": "VulnerabilityOverflow", "error": null}
  [FAILED] in [It] - /Users/padlar/sandbox/image-scanner-operator/internal/controller/stas/scan_job_controller_test.go:103 @ 02/02/23 11:35:50.519
  << Timeline

  [FAILED] Expected
      <string>: Stalled
  to equal
      <string>: Stalled2
  In [It] at: /Users/padlar/sandbox/image-scanner-operator/internal/controller/stas/scan_job_controller_test.go:103 @ 02/02/23 11:35:50.519
```

And with the following ZAP settings -
```
  TRIVY_IMAGE: ghcr.io/aquasecurity/trivy:0.36.1
  ZAP_ENCODER: json
  ZAP_LOG_LEVEL: info
  ZAP_TIME_ENCODING: iso8601
```
Debug lines are not printed out
```
2023-02-02T10:29:30.389Z	INFO	Starting EventSource	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "source": "kind source: *v1.Job"}
2023-02-02T10:29:30.389Z	INFO	Starting Controller	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job"}
2023-02-02T10:29:30.388Z	INFO	Starting EventSource	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "source": "kind source: *v1.PartialObjectMetadata"}
2023-02-02T10:29:30.389Z	INFO	Starting Controller	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod"}
2023-02-02T10:29:30.599Z	INFO	Starting workers	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "worker count": 1}
2023-02-02T10:29:30.599Z	INFO	Starting workers	{"controller": "containerimagescan", "controllerGroup": "stas.statnett.no", "controllerKind": "ContainerImageScan", "worker count": 1}
2023-02-02T10:29:30.600Z	INFO	Starting workers	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "worker count": 1}




2023-02-02T10:46:26.593Z	INFO	Reconciling	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"nginx-748c667d99-r4mwl","namespace":"kuttl-test"}, "namespace": "kuttl-test", "name": "nginx-748c667d99-r4mwl", "reconcileID": "84a34d63-bc03-4915-8b9c-26d4986599bc"}
2023-02-02T10:46:28.738Z	INFO	Reconciling	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"nginx-748c667d99-r4mwl","namespace":"kuttl-test"}, "namespace": "kuttl-test", "name": "nginx-748c667d99-r4mwl", "reconcileID": "3910c7a0-fe37-46d2-ab4e-4d5e30eb021f"}
2023-02-02T10:46:28.770Z	INFO	Reconciling	{"controller": "containerimagescan", "controllerGroup": "stas.statnett.no", "controllerKind": "ContainerImageScan", "ContainerImageScan": {"name":"deployment-nginx-nginx-a2924","namespace":"kuttl-test"}, "namespace": "kuttl-test", "name": "deployment-nginx-nginx-a2924", "reconcileID": "4e1e4433-5c7a-4184-bba0-6534251ca0fc"}
2023-02-02T10:46:43.923Z	INFO	Reconciling	{"controller": "job", "controllerGroup": "batch", "controllerKind": "Job", "Job": {"name":"deployment-nginx-nginx-a2924-c2bd1","namespace":"image-scanner-jobs"}, "namespace": "image-scanner-jobs", "name": "deployment-nginx-nginx-a2924-c2bd1", "reconcileID": "7827afc4-25a3-4e4a-bf6a-fd264366aa29"}
```

**Comment by erikgb** [comment]
Nice! So this additional logging is just for the Go tests. I see.

**Review by erikgb — APPROVED** [review]

**Pull request merged**
