### PR TITLE
test(e2e): replace kuttl with chainsaw

### PR DESCRIPTION
**Pull request by eddycharly**
This PR adds chainsaw tests support.

### CODE REVIEW

**Comment by erikgb** [comment]
Thanks a lot @eddycharly! Appreciated! If you fix the linting issues I will be more than happy to merge this. Let's have both kuttl and chainsaw for now. I can remove one of them later - probably kuttl tests.

**Comment by erikgb** [comment]
@eddycharly We discussed this PR in our stand-up today, and we decided that we want to fully migrate the e2e-tests in this project from kuttl to chainsaw. Are you able to update the PR so it _replaces_ the kuttl tests? We cannot have duplicate tests anyway - as that will be painful to maintain.

**Comment by erikgb** [comment]
LGTM, thanks a lot @eddycharly!

**Review by erikgb — APPROVED** [review]

**Comment by eddycharly** [comment]
Thanks @erikgb for your support !

BTW, a bit of support is always welcome, you can open a PR to add yourself in https://github.com/kyverno/chainsaw/blob/main/ADOPTERS.md if you can/want (no obligations of course).

Let me know if you want more help from us ❤️

**Pull request merged**
